### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by siffegh** [hemiola314/expand-all#1]
Only place it seems to work is on Pages, maybe somewhat on Profiles but not on News Feed or most importantly to me, Groups.

**Comment by hemiola314** [comment]
It works for me. See http://com.hemiola.com/2015/08/29/expand-all/#troubleshooting. In particular, did it used to work for you, and stopped?

**Comment by siffegh** [comment]
Yes, it used to work, then stopped recently. I am using the latest bookmarklet am logged in. This is from a clean FF profile, no extensions enabled.

Console log from a group (ctrl-shift-k):
Responses = 0 3;}let div=document.createElement("div");div.id=this.id;div.style.direction="ltr";div.style.position="fixed";div.style.zIndex="999999";div.style.left=x+"px";div.style.width=WANT_W+"px";div.style.top=y+"px";div.style.height=WANT_H+"px";div.style.color=":1:6829

Console log from a Page, or at least part of it:
click (1 left): See More 3;}let div=document.createElement("div");div.id=this.id;div.style.direction="ltr";div.style.position="fixed";div.style.zIndex="999999";div.style.left=x+"px";div.style.width=WANT_W+"px";div.style.top=y+"px";div.style.height=WANT_H+"px";div.style.color=":1:6829

Programmer for one extension I use suggests this:
POST_ARTICLE cannot rely on [role=article][class=lzcic4wl] because extensions may add classes. Use .lzcic4wl[role=article]:not(.j83agx80)

**Comment by siffegh** [comment]
More from programmer:

That issue could clash with all sorts of extensions. Same with anywhere else he relies on an element having a precise class list, which appears to be there & the 2nd 'selector =' in ensureCommentsShowingNew()

**Comment by hemiola314** [comment]
It works for me, and I’m not going to make changes that I can’t verify. I understand almost nothing of your description of what doesn’t work. Here are some URLs that expand for me; I’m curious if these don’t work for you:
https://www.facebook.com/groups/SALVUS/permalink/1045334152560759/
https://www.facebook.com/MarjorieTaylorGreene/posts/2547514125538682
https://www.facebook.com/Coca-Cola/photos/a.10150567797523306/10153099001083306/
https://www.facebook.com/newspaperscom/photos/a.312842978821852/2325780974194699/
https://www.facebook.com/melina.barratt/posts/10156802298768548/
https://www.facebook.com/yuri.biriukov/posts/1700509770217833

**Comment by siffegh** [comment]
OK, yours all work on FF, Chrome, and Opera (but not Vivaldi). But there's something weird with FF; no matter where  am on FB, sometimes I have to click 'End' a few times, then 'Home' before it works. So let's consider it a local issue? TYVM :-)

**Comment by hemiola314** [comment]
I still don’t know what didn’t work before, and I don’t know what clicking ‘End’ and ‘Home’ refers to. I’ll close this for now.
