### ISSUE TITLE
expanded pinned post but not other posts 

### ISSUE THREAD

**Issue by mginabluebox** [hemiola314/expand-all#2]
Hello,

I was trying the bookmarklet on this page:
https://www.facebook.com/CyprusMail/
It expanded all comments and replies for the Pinned Post ("Expanding: Topmost post"), but then it stops and doesn't do the Other Posts. Can you look into this issue?

Thank you!

**Comment by hemiola314** [comment]
I’ve confirmed the problem. I will fix it, but it might take a few days to make sure other cases are not broken (whack-a-mole). This is the ugliest, hairiest, and most tenuous code of the bookmarklet.

**Comment by hemiola314** [comment]
I believe I fixed it.
http://com.hemiola.com/bookmarklet/
