### ISSUE TITLE
Feature Request: blur/make anonymous every profile pics and names

### ISSUE THREAD

**Issue by fyhtma** [hemiola314/expand-all#4]
Thanks for your work!

However, sometimes when I expand the response section on the FB, I also want to share the view of that section somewhere. But I don't want people to know names/images of the commentators. Would be great if you could add an option to make comments anonymous automatically, thanks!

**Comment by hemiola314** [comment]
IMO, that (i.e., anonymizing) belongs in its own bookmarklet rather than merging it as an option into this one.

**Comment by hemiola314** [comment]
Closed due to inactivity.
