### ISSUE TITLE
Feature Request: Expand text from post "see more" bookmarklet.

### ISSUE THREAD

**Issue by mataka123** [hemiola314/expand-all#6]
It would be nice to see complete text without click "see more" each time.

**Comment by hemiola314** [comment]
Being that that’s a standard feature, I’m assuming you mean that you found a URL where it doesn’t work. If you provide a URL, I will look at it.

**Comment by SunFox14** [comment]
Came here to ask about expanding "see more"....but currently I can't get it to work at all on a specific post, and unfortunately it's in a private group.

**Comment by hemiola314** [comment]
Are you saying it works most of the time but occasionally does not?

**Comment by hemiola314** [comment]
Can you try this bookmarklet? I've been modifying how 'See more' gets clicked but haven't checked it in.

http://com.hemiola.com/bookmarklet2/

**Comment by SunFox14** [comment]
Just tried it on several of my groups, the previous one didn't work on any, but the new one does!

**Comment by hemiola314** [comment]
Okay. I still don't know if you were ever successful, such as expanding the URL above (https://www.facebook.com/theguardian/posts/pfbid0322YLJfSvbwQ6YC5nJuby36zTR9ZfJ8rBMvvykRqBY95kwHGCvTVqWhGtWgc8Lczsl).

Anyway, I have posted/checked in the change (2022-10-20). There is no need for you to update.
